### ISSUE TITLE
Discord Alt Domain

### ISSUE THREAD

**Issue by ghost** [tutyamxx/is-discord-invitation#3]
Discord also owns watchanimeattheoffice.com which allows users to use https://watchanimeattheoffice.com/invite/inv
If you could add this to the blacklist that would be amazing

**Comment by ghost** [comment]
Id use "(?:https?:\\/\\/)?(?:www\\.)?(discord\\.(?:gg|io|me|li|link|list|media)|(?:discord(?:app)?|watchanimeattheoffice)\\.com\\/invite)\\/(.+[a-zA-Z0-9])" as a starter as it also brings in 3rd party invite services

**Comment by tutyamxx** [comment]
Yeah, thanks for letting me know, discord also has this domain for nitro redirects -> https://bigbeans.solutions/

**Comment by ghost** [comment]
Oh wow I had no idea that https://bigbeans.solutions/ was a thing

**Comment by tutyamxx** [comment]
Updated. See 711e2c5379e476d5b66977b65783703228c7bcc2 and thanks for the info.

**Comment by ghost** [comment]
I hate to reopen this and I am not exactly sure what your filter catches rn-
But it does seem like these are also official and can be used for invites
discord.co/invite/
discord.media/invite/
discordapp.net/invite/
discordsays.com/invite/

**Comment by tutyamxx** [comment]
they can, but a discord invite usually has a hash (between 3 and 16 characters) after the `/invite/` path so in theory, is not an invite, is just a link with no invitation. But thanks for the links, I will update again XD

**Comment by ghost** [comment]
ikik I just didn't know what to use as a placeholder bcs almost everything has been taken as a vanity lol
